name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Backend
        run: cargo build --release
        working-directory: backend
      - name: Download Frontend Deps
        run: yarn install
        working-directory: gui
      - name: Build Frontend
        run: yarn build
        working-directory: gui
